export const products = [
    {
      id: 1,
      name: "KACAMATA",
      category: "Aksesori",
      price: 150000,
      image: "/images/product1.jpg",
      isCart: false,
      description: "Kacamata ini bisa menjadi salah satu fashion yang cocok di gunakan di berbagai musim.",
    },
    {
      id: 2,
      name: " TOPI PANTAI",
      category: "Aksesori",
      price: 100000,
      image: "/images/product8.jpg",
      isCart: false,
      description: "Topi Pantai ini bisa menjadi salah satu fashion yang cocok di gunakan ketika kita berlibur ke pantai.",
    },
    {
      id: 3,
      name: "STRIPED PATTERN SCARF",
      category: "Aksesori",
      price: 300000,
      image: "/images/product9.jpg",
      isCart: false,
      description: "Striped Pattern Scarf merupakan salah satu fashion yang di gunakan pada bagian tubuh yaitu di leher.",
    },
    {
      id: 4,
      name: "PERHIASAN",
      category: "Aksesori",
      price: 1000000,
      image: "/images/product14.jpg",
      isCart: false,
      description: "Perhaisan merupakan salah satu fashion yang memberikan kesan estetika pada tubuh.",
    },
    {
      id: 5,
      name: "SELOP JAWA",
      category: "Alas Kaki",
      price: 100000,
      image: "/images/product6.jpg",
      isCart: false,
      description: "Selop Jawa merupakan salah satu fashion berupa alas kaki yang berasal dari Jawa.",
    },
    {
      id: 6,
      name: "GETA",
      category: "Alas Kaki",
      price: 150000,
      image: "/images/product15.jpg",
      isCart: false,
      description: "Geta merupakan salah satu fashion berupa alas kaki yang berasal dari Jepang.",
    },
    {
      id: 7,
      name: "TEROMPAH",
      category: "Alas Kaki",
      price: 100000,
      image: "/images/product7.jpg",
      isCart: false,
      description: "Terompah merupakan salah satu fashion berupa alas kaki yang berasal dari Malaysia.",
    },
    {
      id: 8,
      name: "ZORI",
      category: "Alas Kaki",
      price: 200000,
      image: "/images/product2.jpg",
      isCart: false,
      description: "Zori merupakan salah satu fashion berupa alas kaki yang berasal dari Jepang.",
    },
    {
      id: 9,
      name: "KIMONO",
      category: "Baju Adat",
      price: 350000,
      image: "/images/product3.jpg",
      isCart: false,
      description: "Kimono merupakan salah satu baju adat khas Jepang yang cocok di gunakan ketika kita berkunjung ke tempat destinasi peninggalan bersejarah.",
    },
    {
      id: 10,
      name: "HANBOOK",
      category: "Baju Adat",
      price: 400000,
      image: "/images/product4.jpg",
      isCart: false,
      description: "Hanbook merupakan salah satu baju adat khas Korea yang cocok di gunakan ketika kita berkunjung ke tempat destinasi peninggalan bersejarah.",
    },
    {
      id: 11,
      name: "KEBAYA",
      category: "Baju Adat",
      price: 300000,
      image: "/images/product5.jpg",
      isCart: false,
      description: "Kebaya merupakan salah satu baju adat khas Korea yang cocok di gunakan ketika kita berkunjung ke tempat destinasi peninggalan bersejarah.",
    },
    {
      id: 12,
      name: "Kain Ulos",
      category: "Baju Adat",
      price: 200000,
      image: "/images/product13.jpg",
      isCart: false,
      description: "Kain Ulos merupakan salah satu baju adat khas Sumatera Utara yang cocok di gunakan ketika kita berkunjung ke tempat destinasi peninggalan bersejarah.",
    },
    {
      id: 13,
      name: "Ransel",
      category: "Tas",
      price: 85000,
      image: "/images/product10.jpg",
      isCart: false,
      description: "Ransel merupakan salah satu tas yang nyaman untuk di gunakan dan bisa untuk menempatkan banyak barang.",
    },
    {
      id: 14,
      name: "Tas Selempang",
      category: "Tas",
      price: 80000,
      image: "/images/product11.jpg",
      isCart: false,
      description: "Tas Selempang merupakan salah satu tas yang nyaman untuk di gunakan berpergian bersama teman.",
    },
    {
      id: 15,
      name: "Handbag",
      category: "Tas",
      price: 90000,
      image: "/images/product12.jpg",
      isCart: false,
      description: "Handbag merupakan salah satu tas yang nyaman untuk di gunakan ketika kita party.",
    },
    {
      id: 16,
      name: "Dompet",
      category: "Tas",
      price: 55000,
      image: "/images/product16.jpg",
      isCart: false,
      description: "Dompet merupakan salah satu yang termaksuk ke dalam kategori tas untuk menyimpan uang maupun kartu.",
    },
  ];